version: "3"

services:
  api:
    tty: true
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - code_share:/var/public
    restart: always
  
  sandbox:
    tty: true
    build:
      context: ./sandbox
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - code_share:/var/public
    restart: always

volumes:
  code_share:
    