version: "3"

services:
  api:
    tty: true
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./app:/app
    restart: always
  
  sandbox:
    tty: true
    build:
      context: ./sandbox
      dockerfile: Dockerfile
    ports:
      - 6080:80
    volumes:
      - /dev/shm:/dev/shm
    restart: always
    
  url:
    tty: true
    build:
      context: ./url
      dockerfile: Dockerfile
    ports:
      - 10000:10000
    volumes:
      - ./url:/url
    restart: always